domain: startups
type: business
narrativity:
  structural: 0.6
  temporal: 0.6
  agency: 0.6
  interpretive: 0.6
  format: 0.6
data:
  text_fields:
  - text
  outcome_field: outcome
  context_features: null
  name_field: null
outcome_type: continuous
transformer_augmentation: []
custom_validators: []
description: null
sample_size: null
pi: 0.5999999999999999
perspectives:
- director
- audience
- critic
quality_methods:
- weighted_mean
- ensemble
scales:
- micro
- meso
- macro
aggregation_method: importance_weighted
