domain: housing
type: nominative
narrativity:
  structural: 0.36000000000000004
  temporal: 0.315
  agency: 0.27
  interpretive: 0.36000000000000004
  format: 0.315
data:
  text_fields:
  - text
  outcome_field: outcome
  context_features: null
  name_field: null
outcome_type: continuous
transformer_augmentation: []
custom_validators: []
description: null
sample_size: null
pi: 0.32400000000000007
perspectives:
- director
- audience
- critic
quality_methods:
- weighted_mean
- ensemble
scales:
- micro
- meso
- macro
aggregation_method: importance_weighted
